<?php

namespace AppBundle\Repository;

/**
 * TipoEntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEntidadRepository extends \Doctrine\ORM\EntityRepository
{
}
